### ISSUE TITLE
Skip object detection frames.

### ISSUE THREAD

**Issue by nathancooperjones** [wmuron/motpy#8]
Thanks for developing `motpy` - I have found it is working great so far and is simple to use. 

I am trying to use the tool to speed up my object detection pipeline using a deep learning model. I am hoping to be able to have to do inference on the deep learning model every few frames, and rely on object tracking for the frames in between. 

Is there a way to update the tracker in `motpy` without having to provide a new set of `detections`? 

Thank you!

**Comment by wmuron** [comment]
Hi Nathan, you can easily achieve that, but keep in mind that the active tracks might be more jittery and it is definitely more prone to misdetection errors (because the trackers are corrected less often). You also might need to spend a bit more time tuning the params to the expected motion of your domain objects.

The easiest way to adapt your code is to simply pass empty detections list, when the detector is not running; e.g. in the example below detections will be calculated only on every 3rd frame. 
```python
...
if frame_idx % 3 == 1:
    bboxes = face_detector.process_image(frame)
    detections = [Detection(box=bbox) for bbox in bboxes]
    logger.debug(f'detections: {detections}')
else:
    detections = []

tracker.step(detections)
tracks = tracker.active_tracks(min_steps_alive=3, max_staleness_to_positive_ratio=10.)
logger.debug(f'tracks: {tracks}')
...
```
However, in this case you need to keep even older tracks alive, so make sure that you tune the staleness-related parameters. You can set `max_staleness` to a larger number in MultiObjectTracker initialization (similar to `MultiObjectTracker(..., tracker_kwargs={'max_staleness': 30})` and pass greater `max_staleness_to_positive_ratio` to `active_tracks(...)` method (e.g. `max_staleness_to_positive_ratio=10` should work just fine).
